// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Feane.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222042753_FixProductImageUrlCorrect")]
    partial class FixProductImageUrlCorrect
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Feane.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "pizza",
                            DescriptionKey = "Dish_PizzaDescription",
                            ImageUrl = "images/f1.png",
                            NameKey = "Dish_DeliciousPizza",
                            Price = 20m
                        },
                        new
                        {
                            Id = 2,
                            Category = "burger",
                            DescriptionKey = "Dish_BurgerDescription",
                            ImageUrl = "images/f2.png",
                            NameKey = "Dish_DeliciousBurger",
                            Price = 15m
                        },
                        new
                        {
                            Id = 3,
                            Category = "pizza",
                            DescriptionKey = "Dish_PizzaDescription",
                            ImageUrl = "images/f3.png",
                            NameKey = "Dish_DeliciousPizza",
                            Price = 17m
                        },
                        new
                        {
                            Id = 4,
                            Category = "fries",
                            DescriptionKey = "Dish_FriesDescription",
                            ImageUrl = "images/f5.png",
                            NameKey = "Dish_FrenchFries",
                            Price = 10m
                        },
                        new
                        {
                            Id = 5,
                            Category = "pasta",
                            DescriptionKey = "Dish_PastaDescription",
                            ImageUrl = "images/f4.png",
                            NameKey = "Dish_DeliciousPasta",
                            Price = 18m
                        },
                        new
                        {
                            Id = 6,
                            Category = "pizza",
                            DescriptionKey = "Dish_PizzaDescription",
                            ImageUrl = "images/f6.png",
                            NameKey = "Dish_DeliciousPizza",
                            Price = 15m
                        },
                        new
                        {
                            Id = 7,
                            Category = "burger",
                            DescriptionKey = "Dish_BurgerDescription",
                            ImageUrl = "images/f8.png",
                            NameKey = "Dish_TastyBurger",
                            Price = 14m
                        },
                        new
                        {
                            Id = 8,
                            Category = "burger",
                            DescriptionKey = "Dish_BurgerDescription",
                            ImageUrl = "images/f7.png",
                            NameKey = "Dish_TastyBurger",
                            Price = 12m
                        },
                        new
                        {
                            Id = 9,
                            Category = "pasta",
                            DescriptionKey = "Dish_PastaDescription",
                            ImageUrl = "images/f9.png",
                            NameKey = "Dish_DeliciousPasta",
                            Price = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
